version: '3.9'
services:
  app:
    image: zeecosmetics
    container_name: golang_container
    env_file:
      - .env
    tty: true
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - learning
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - learning
networks:
  learning:
    driver: bridge