// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"clean/pkg/api"
	"clean/pkg/api/handler"
	"clean/pkg/config"
	"clean/pkg/db"
	"clean/pkg/repository"
	"clean/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewuserRepository(gormDB)
	cartRepository := repository.NewCartRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository, cartRepository, cfg)
	userHandler := handler.NewUserHandler(userUseCase)
	otpRepository := repository.NewOtprepository(gormDB)
	otpUseCase := usecase.NewOtpUseCase(cfg, otpRepository)
	otpHandler := handler.NewOtpHandler(otpUseCase)
	productRepository := repository.NewProductRepository(gormDB)
	productUseCase := usecase.NewProductUseCase(productRepository, cfg)
	productHandler := handler.NewProductHandler(productUseCase)
	cartUseCase := usecase.NewCartUseCase(cartRepository, productRepository)
	cartHandler := handler.NewCartHandler(cartUseCase)
	orderRepository := repository.NewOrderRepository(gormDB)
	orderUseCase := usecase.NewOrderUseCase(orderRepository, cartRepository, userRepository)
	orderHandler := handler.NewOrderHandler(orderUseCase)
	serverHTTP := http.NewServerHTTP(userHandler, otpHandler, productHandler, cartHandler, orderHandler)
	return serverHTTP, nil
}
